---
title: "Plan détaillé des séances"
output: rmarkdown::html_vignette
toc:
  depth: 2
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\VignetteIndexEntry{Plan détaillé des séances}
---

## Semaine 4


### Avant le cours:

- Capsules vidéo 2e, 2f, 2g
- Notes de cours: chapitre 2 (sections 5-7)

### En classe:

- [Tests pour interactions](https://raw.githubusercontent.com/lbelzile/modstat/master/code/60604_interactions.sas)
- Atelier sur les interactions (Exercice 2.8)

## Après le cours:

- Exercices 2.5-2.7

---

## Semaine 3

### Avant le cours:

- Capsules vidéo 2d, 3
- [Notes de cours (anglais)](https://lbelzile.github.io/math60604a): chapitre 3, chapitre 2 (section 4)

### En classe:

- [Démo **R**: distribution d'échantillonage des MCO, vraisemblance profilé pour un coefficient $\beta$](https://raw.githubusercontent.com/lbelzile/modstat/master/code/60604_vraisemblance_profile_beta.R)
- [Interprétation des tests d'une sortie **SAS** pour les données `assurance`](https://raw.githubusercontent.com/lbelzile/modstat/master/code/60604_interpretation_tests.sas)
- [**Understanding Maximum Likelihood** by Kristoffer Magnusson](https://rpsychologist.com/d3/likelihood/)

## Après le cours

- Série d'exercices 3
- [Tests à l'aide de modèles linéaires](https://lindeloev.github.io/tests-as-linear/)

---

## Semaine 2

### Avant le cours: 

- Capsules vidéo 2a, 2b (2c optionnelle)
- Notes de cours: chapitre 2, sections 2.1 à 2.3

### En classe:

- Interprétation des coefficients (données `intention`)
- Retour sur les données `assurance`
- [Diagrammes de régression partielle](https://raw.githubusercontent.com/lbelzile/modstat/master/code/60604_diagramme_regression_partielle.sas)

### Après le cours: 

- Exercices 2.1-2.4
- [xkcd: Curve-fitting](https://xkcd.com/2048/)

---

## Semaine 1

### Avant le cours: 

- Capsule vidéos: 0, 1a, 1b, 1c
- Notes de cours: chapitre 1 et annexe A
- Créez un compte pour **SAS** onDemand 
- Complétez l'[Introduction à **SAS**](https://lbelzile.github.io/modstat/articles/introSAS.html)

### En classe:

- Présentation et pratique des outils pédagogique (Zoom / Etherpad / Wooclap / SAS onDemand)
- [Atelier de visualisation (groupe)](https://github.com/lbelzile/modstat/raw/master/atelier/graphiques/graphics.zip)

### Après le cours

- Quiz 1 (`intro`)
- Exercice 1.4 (a) et (b) avec **SAS**. *Note: cette série d'exercices est probablement difficile à l'heure actuelle, mais vous devriez être en mesure de la compléter dans quelques semaines.*


### Lectures additionnelles:

- [Chapitre 1 de *Data Visualization: A practical introduction* par Kieran Healy](https://socviz.co/lookatdata.html#lookatdata)
- [Tests de permutation](https://www.jwilber.me/permutationtest/)
- [DataViz Cheatsheet](https://policyviz.com/2018/08/07/dataviz-cheatsheet/)
- [Chapitre 7 de _**R** for Data Science_ par Garrett Grolemund et Hadley Wickham](https://r4ds.had.co.nz/)

### Autres références:

- [Chapitre 3 de _**R** for Data Science_ par Garrett Grolemund et Hadley Wickham](https://r4ds.had.co.nz/)
- [*Fundamentals of Data Visualization* par Claus O. Wilke](https://clauswilke.com/dataviz/)
- [Do's and don'ts of making effective graphics](https://stat545.com/effective-graphs.html)
- [Financial Times Visual Vocabulary](	https://github.com/ft-interactive/chart-doctor/tree/master/visual-vocabulary)
- [BBC R Cookbook (optionnel)](https://bbc.github.io/rcookbook/)
