/* CD4 counts  */
data cd4;
set statmod.cd4;
if (tss >= 0) then sero = 1;
else sero = 0;
tsscarre = tss*tss;
run;

* Model (a); 
proc mixed data=cd4 method = ml;
class id;
model cd4 = sero;
repeated / type=sp(pow)(tss) subject = id r=1;
random intercept / subject=id v=1;
run;
* Model (b); 
proc mixed data=cd4 method = ml;
class id;
model cd4 = tss;
repeated / type=sp(pow)(tss) subject = id r=1;
random intercept / subject=id v=1;
run;
* Model (c); 
proc mixed data=cd4 method = ml;
class id;
model cd4 = sero tss;
repeated / type=sp(pow)(tss) subject = id r=1;
random intercept / subject=id v=1;
run;
* Model (d); 
proc mixed data=cd4 method = ml;
class id;
model cd4 = sero|tss;
repeated / type=sp(pow)(tss) subject = id r=1;
random intercept / subject=id v=1;
run;
* Model (e); 
proc mixed data=cd4 method = ml;
class id;
model cd4 = sero sero*tss;
repeated / type=sp(pow)(tss) subject = id r=1;
random intercept / subject=id v=1;
run;
* Model (f); 
proc mixed data=cd4 method = ml;
class id;
model cd4 = tss sero*tss;
repeated / type=sp(pow)(tss) subject = id r=1;
random intercept / subject=id v=1;
run;
* Model (g) - best model according to BIC; 
proc mixed data=cd4 method = ml;
class id;
model cd4 = sero tsscarre*sero tss*sero;
repeated / type=sp(pow)(tss) subject = id r=1;
random intercept / subject=id v=1;
run;
* Model (h); 
proc mixed data=cd4 method = ml;
class id;
model cd4 = tsscarre*sero tss*sero;
repeated / type=sp(pow)(tss) subject = id r=1;
random intercept / subject=id v=1;
run;